version: '2'

services:
    # MySQL Server
    mysql:
        image: mysql:5.6
        restart: always
        container_name: "akeneo_pim_mysql"
        environment:
            - "MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD"
        command: "--max_allowed_packet=1000M --connect_timeout=72"
        volumes:
            - "./.mysql_data/mysql:/var/lib/mysql"
            - "./conf/mysql/:/etc/mysql/conf.d"
        ports:
            - "3306:3306"
        networks:
            akeneo_network:
                aliases:
                    - mysql.db


    # Akeneo Pim
    akeneo:
        build: .
        image: pim/php-fpm-apline
        container_name: "akeneo_pim_app"
        environment:
            - "COMPOSER_CACHE_DIR=/cache"
        volumes:
            - "${SOURCE_PATH}:/var/www/pim/"
            - "./conf/php/php.ini:/usr/local/etc/php/php.ini"
            - "./.composer/cache:/cache"
        working_dir: /var/www/pim/
        user: "$USER_ID"
        networks:
            akeneo_network:
                aliases:
                    - akeneo.pim

    nginx:
        image: nginx:alpine
        container_name: "akeneo_pim_nginx"
        volumes:
            - "./conf/nginx/nginx-site.conf:/etc/nginx/conf.d/default.conf:ro"
        ports:
            - 80:80
            - 443:443
        depends_on:
            - akeneo
        volumes_from:
            - akeneo:ro
        networks:
           - akeneo_network

# Uncomment to use Selenium / Behat setup
#     selenium:
#         image: selenium/standalone-firefox-debug:2.53.1
#         ports:
#             - 4444:4444
#             - 5901:5900
#         environment:
#             - "no_proxy=localhost"
#         user: "$USER_ID"
#         container_name: akeneo_pim_selenium
#         networks:
#             akeneo_network:
#
# Uncomment this lines if you want Xdebug (Dev)
#       # X-DEBUG Proxy for remote debugging php-fpm
#    dbgpproxy:
#        image: christianbladescb/dbgpproxy
#        restart: always
#        container_name: "akeneo_pim_xdebug"
#        ports:
#            - "9001:9000"
#        networks:
#            - akeneo_network

volumes:
    mysql_data:
        driver: local

networks:
    akeneo_network:
