version: '2'

services:
    # MySQL Server
    mysql:
        image: mysql:5.6
        restart: always
        container_name: "akeneo_pim_mysql"
        env_file: "./.env"
        command: "--max_allowed_packet=1000M --connect_timeout=72"
        labels:
            - com.pim.alias.mysql
        volumes:
            - "./.mysql_data/mysql:/var/lib/mysql"
            - "./conf/mysql/:/etc/mysql/conf.d"
        networks:
            akeneo_network:
                ipv4_address: 192.168.231.20
                aliases:
                    - mysql.db


    # Akeneo Pim
    akeneo:
        build: .
        image: pim/docker-akeneo-apline
        container_name: "akeneo_pim_app"
        volumes:
            - "${SOURCE_PATH}:/var/www/pim/"
            - "./scripts:/var/www/html/scripts"
            - "./conf:/var/www/html/conf"
        labels:
            - com.pim.alias.web_app
        networks:
            akeneo_network:
                ipv4_address: 192.168.231.10
                aliases:
                       - akeneo.pim
#
# Uncomment this lines if you want Xdebug (Dev)
#       # X-DEBUG Proxy for remote debugging php7fpm
#    dbgpproxy:
#        image: christianbladescb/dbgpproxy
#        restart: always
#        container_name: "akeneo_pim_xdebug"
#        ports:
#            - "9002:9001"
#        networks:
#            - akeneo_network


# volumes:
    
networks:
    akeneo_network:
        external:
            name: my_akeneo_network
       
